export const CLASSES = {
  warrior: {
    label: 'Warrior',
    role: 'Tank',
    heart: 8,
    defense: 10,
    attackDie: 10,
    attackName: 'Cleave',
    trick: 'Ignore Pain — once per fight, ignore a hit completely.',
    skill: 'Rage — after 3 consecutive hits, roll an extra d10 and remove that many additional Heart bricks.',
  },
  cleric: {
    label: 'Cleric',
    role: 'Healer',
    heart: 7,
    defense: 8,
    attackDie: 6,
    attackName: 'Mace Strike',
    trick: 'Heal — once per fight, restore 1 Heart brick to an ally instead of attacking.',
    skill: 'AoE — once per fight, roll your damage die once and remove that many bricks from every monster in your location.',
  },
  priest: {
    label: 'Priest',
    role: 'Healer',
    heart: 6,
    defense: 7,
    attackDie: 6,
    attackName: 'Smite',
    trick: 'Heal — once per fight, restore 1 Heart brick to an ally instead of attacking.',
    skill: 'Party Shield — once per fight, block one hit for every ally.',
  },
  druid: {
    label: 'Druid',
    role: 'Hybrid',
    heart: 7,
    defense: 7,
    attackDie: 6,
    attackName: 'Bramble Lash',
    trick: 'Wild Shape — once per fight, become Bear (Attack becomes d10) or Panther (next attack auto-hits).',
    skill: "Vine Snare — once per fight, root a monster; it skips its next attack, then loses 1 Heart brick when the vines break.",
  },
  monk: {
    label: 'Monk',
    role: 'Hybrid',
    heart: 7,
    defense: 8,
    attackDie: 6,
    attackName: 'Palm Strike',
    trick: 'Harmony & Discord — on a hit, choose: deal damage, or heal an ally 1 Heart brick instead.',
    skill: 'Adept — once per fight, dodge one otherwise-fatal blow completely.',
  },
  rogue: {
    label: 'Rogue',
    role: 'Melee DPS',
    heart: 6,
    defense: 7,
    attackDie: 6,
    attackName: 'Twin Blades',
    trick: 'Sneak Attack — your first hit each fight always succeeds.',
    skill: "Cheat Death — once per fight, if you'd hit 0 Heart bricks, stay at 1 instead.",
  },
  bard: {
    label: 'Bard',
    role: 'Support',
    heart: 6,
    defense: 7,
    attackDie: 6,
    attackName: 'Songbook Smack',
    trick: 'Ballad: Inspire — once per fight, let an ally reroll any one roll.',
    skill: "Ballad: Fury — once per fight, every ally's next hit deals max damage automatically.",
  },
  hunter: {
    label: 'Hunter',
    role: 'Ranged DPS',
    heart: 6,
    defense: 8,
    attackDie: 6,
    attackName: 'Training Bow',
    trick: 'Steady Aim — reroll one missed attack per fight.',
    skill: 'Rapid Fire — recover 1 saved arrow per monster defeated (max 2); spend one to roll your damage die twice.',
  },
  engineer: {
    label: 'Engineer',
    role: 'Ranged Support',
    heart: 6,
    defense: 8,
    attackDie: 10,
    attackName: 'Gearshot',
    trick: 'Rummage — collect 1 part each time you defeat a monster or search successfully.',
    skill: 'Deploy — after 3 parts, build a robot (Atk d6 / Def 8 / Heart 3): Damage Bot or Support Bot.',
  },
  mage: {
    label: 'Mage',
    role: 'Ranged DPS',
    heart: 5,
    defense: 7,
    attackDie: 10,
    attackName: 'Fireball',
    trick: 'Spectral Shift — once per fight, redirect a hit to another hero in your location; skip your next turn.',
    skill: "Comet Strike — once per fight, roll vs. one monster's Defense; a hit also Frost-Splashes every other monster your roll would also beat, freezing them for 1 turn.",
  },
};
